/* Interpretaciones por astro × signo (orden: Aries..Piscis) — Deicy Carta Astral */
window.INTERP={
 Sol:[
  'Tu esencia es pionera y valiente: necesitás iniciar, competir y ser la primera. Brillás cuando actuás sin pedir permiso.',
  'Tu esencia es serena y sensorial: brillás construyendo cosas sólidas, disfrutando lo lindo y yendo a tu propio ritmo.',
  'Tu esencia es curiosa y comunicativa: brillás aprendiendo, hablando y conectando ideas y personas.',
  'Tu esencia es protectora y sensible: brillás cuidando a los tuyos y creando un hogar donde todos se sientan seguros.',
  'Tu esencia es cálida y creativa: naciste para brillar, crear y que te vean; el escenario es tu lugar.',
  'Tu esencia es analítica y servicial: brillás mejorando, ordenando y resolviendo lo que otros pasan por alto.',
  'Tu esencia es diplomática y estética: brillás en los vínculos, buscando equilibrio, belleza y armonía.',
  'Tu esencia es intensa y profunda: brillás transformándote, yendo al fondo de todo y sin miedo a la sombra.',
  'Tu esencia es aventurera y filosófica: brillás explorando, aprendiendo y buscándole sentido a la vida.',
  'Tu esencia es ambiciosa y responsable: brillás construyendo a largo plazo, con disciplina y metas claras.',
  'Tu esencia es original y libre: brillás siendo diferente, pensando distinto y aportando al colectivo.',
  'Tu esencia es soñadora y empática: brillás imaginando, sintiendo y conectando con algo más grande que vos.'
 ],
 Luna:[
  'Sentís rápido e intenso y necesitás acción: te calma moverte, no quedarte rumiando. Reaccionás en caliente.',
  'Necesitás calma, contacto y estabilidad: te tranquiliza la rutina, lo rico y los abrazos largos.',
  'Procesás las emociones hablándolas y pensándolas: necesitás variedad y conversación para sentirte bien.',
  'Sentís todo en profundidad y necesitás contención: el hogar y los tuyos son tu refugio emocional.',
  'Necesitás cariño, reconocimiento y calidez: te hace bien sentirte querida y especial.',
  'Te sentís segura cuando todo está en orden: cuidás a través de los detalles y de ser útil.',
  'Necesitás armonía y compañía: los conflictos te desestabilizan; buscás paz y vínculos equilibrados.',
  'Sentís de forma intensa y total: necesitás intimidad real y verdad; no te sirve lo superficial.',
  'Necesitás libertad y horizonte: te hace bien viajar, reírte y no sentirte encerrada.',
  'Manejás las emociones con autocontrol: necesitás sentirte capaz; te cuesta mostrarte vulnerable.',
  'Necesitás espacio y libertad emocional: querés a tu manera, sin presiones ni dramas.',
  'Sentís todo y hasta lo ajeno: necesitás momentos de soledad, arte o espiritualidad para descargar.'
 ],
 Mercurio:[
  'Mente rápida y directa: pensás y hablás sin rodeos, decidís en el acto y a veces antes de terminar de escuchar.',
  'Pensás despacio y con los pies en la tierra: te tomás tu tiempo, pero lo que decidís es firme.',
  'Mente ágil y curiosa: hablás, escribís y aprendés con facilidad; te aburre lo lento.',
  'Pensás con la emoción: tu memoria es enorme y comunicás desde lo que sentís.',
  'Te expresás con seguridad y dramatismo: tus palabras tienen brillo y te gusta que te escuchen.',
  'Mente precisa y analítica: detectás errores, ordenás ideas y comunicás con claridad.',
  'Pensás en términos de equilibrio: sopesás todo, buscás el acuerdo y hablás con diplomacia.',
  'Mente investigadora y penetrante: vas al fondo, detectás lo oculto y no te creés lo primero que te dicen.',
  'Pensás en grande: te interesan las ideas, los viajes y el sentido; a veces prometés de más.',
  'Mente estructurada y estratégica: pensás con lógica, a largo plazo y con foco en lo útil.',
  'Mente original e inventiva: pensás distinto, fuera de la caja, y te atraen las ideas del futuro.',
  'Pensás con imágenes e intuición: tu mente es soñadora y creativa, menos lineal que la de otros.'
 ],
 Venus:[
  'Amás con pasión e iniciativa: te gusta conquistar, la chispa y que las cosas pasen ya.',
  'Amás con sensualidad y lealtad: valorás la estabilidad, el contacto y los placeres simples.',
  'Te enamorás por la cabeza: necesitás charla, juego y variedad; la rutina te enfría.',
  'Amás con ternura y entrega: cuidás, contenés y buscás un vínculo que sea hogar.',
  'Amás con generosidad y drama: querés romance, admiración y sentirte el centro de tu pareja.',
  'Amás cuidando los detalles: demostrás cariño con gestos útiles; te cuesta lo demasiado cursi.',
  'Amás la armonía y la pareja: sos romántica, estética y buscás equilibrio y compañía.',
  'Amás con intensidad total: todo o nada, fusión profunda, y fidelidad puesta a prueba.',
  'Amás con libertad y aventura: querés compartir viajes, risas y crecer juntos sin ataduras.',
  'Amás con compromiso y seriedad: vas despacio, pero cuando elegís, es para construir.',
  'Amás distinto y libre: valorás la amistad, la independencia y los vínculos sin etiquetas.',
  'Amás con romanticismo y entrega total: idealizás, te fusionás y das sin medir.'
 ],
 Marte:[
  'Energía pura y directa: vas por lo que querés sin vueltas; impulsiva, valiente y competitiva.',
  'Energía constante y resistente: arrancás lento pero no parás; terca cuando te lo proponés.',
  'Energía mental y dispersa: peleás con palabras, hacés mil cosas a la vez y te aburre la rutina.',
  'Actuás desde la emoción: defendés a los tuyos a muerte, aunque te cueste el enfrentamiento directo.',
  'Energía con brillo y orgullo: actuás con confianza y dramatismo, querés ganar y que se note.',
  'Energía metódica y eficiente: trabajás con precisión y te enoja el desorden y la chapucería.',
  'Te cuesta el conflicto frontal: buscás el acuerdo, pero cuando te decidís sos imparable con tacto.',
  'Energía intensa y estratégica: no perdonás fácil, vas con todo y tu deseo es profundo.',
  'Energía aventurera: actuás con entusiasmo, te lanzás a lo grande y odiás sentirte limitada.',
  'Energía disciplinada y ambiciosa: trabajás duro, con paciencia y foco en la meta.',
  'Energía rebelde e independiente: actuás distinto, defendés causas y odiás que te manden.',
  'Energía suave e intuitiva: actuás de manera indirecta, desde la sensibilidad o la creatividad.'
 ],
 'Júpiter':[
  'Crecés animándote: tu suerte aparece cuando tomás la iniciativa y liderás.',
  'Crecés con paciencia: la abundancia te llega construyendo de a poco y disfrutando lo material.',
  'Crecés aprendiendo y comunicando: tu suerte está en las ideas, los contactos y la palabra.',
  'Crecés cuidando: la abundancia llega por el hogar, la familia y lo emocional.',
  'Crecés brillando: tu suerte aparece cuando te mostrás, creás y ocupás el centro.',
  'Crecés sirviendo y mejorando: la abundancia llega por el trabajo bien hecho y lo útil.',
  'Crecés en los vínculos: tu suerte está en las relaciones, los acuerdos y la belleza.',
  'Crecés transformándote: la abundancia llega cuando te animás a lo profundo y a reinventarte.',
  'Júpiter en su signo: gran optimismo, fe y suerte; crecés viajando, estudiando y enseñando.',
  'Crecés con esfuerzo: la abundancia llega por la disciplina, la carrera y el largo plazo.',
  'Crecés innovando: tu suerte está en lo grupal, lo original y las causas del futuro.',
  'Júpiter cómodo en Piscis: crecés con fe, arte y compasión; suerte ligada a lo espiritual.'
 ],
 Saturno:[
  'Aprendés a manejar tu impulso: tu desafío es la paciencia y construir sin atropellar.',
  'Aprendés sobre la seguridad material: tu desafío es soltar el miedo a no tener y confiar.',
  'Aprendés a enfocar la mente: tu desafío es la constancia y terminar lo que empezás.',
  'Aprendés sobre tus emociones: tu desafío es permitirte sentir y pedir contención.',
  'Aprendés sobre tu valor: tu desafío es confiar en tu brillo sin necesitar aprobación.',
  'Aprendés sobre la autoexigencia: tu desafío es aceptar que no todo tiene que ser perfecto.',
  'Aprendés sobre los vínculos y compromisos: tu desafío es equilibrar dar y recibir.',
  'Aprendés sobre el control y la confianza: tu desafío es soltar y atravesar lo profundo.',
  'Aprendés a sostener tus creencias: tu desafío es comprometerte con un camino y no dispersarte.',
  'Saturno en su signo: gran disciplina y ambición; aprendés sobre responsabilidad y autoridad.',
  'Saturno fuerte: estructurás lo grupal; aprendés sobre la libertad con compromiso.',
  'Aprendés a darle forma a lo difuso: tu desafío es estructurar tus sueños y tu sensibilidad.'
 ],
 Urano:[
  'Tu generación rompe siendo pionera, con energía rebelde e independiente.',
  'Tu generación revoluciona lo material, el dinero y la relación con la tierra.',
  'Tu generación transforma la comunicación, la información y la forma de aprender.',
  'Tu generación cambia la idea de hogar, familia y raíces.',
  'Tu generación reinventa la creatividad, el ego y la forma de brillar.',
  'Tu generación revoluciona el trabajo, la salud y lo cotidiano.',
  'Tu generación transforma los vínculos, la pareja y la idea de igualdad.',
  'Tu generación rompe tabúes sobre el poder, la sexualidad y lo profundo.',
  'Tu generación revoluciona las creencias, la educación y los viajes.',
  'Tu generación transforma las estructuras, las instituciones y la autoridad.',
  'Urano en su signo: generación muy original, tecnológica y rupturista por naturaleza.',
  'Tu generación revoluciona la espiritualidad, el arte y la conciencia colectiva.'
 ],
 Neptuno:[
  'Tu generación sueña con nuevos comienzos y espiritualiza la acción.',
  'Tu generación idealiza lo material y busca conexión espiritual con la naturaleza.',
  'Tu generación difumina los límites de la información y la comunicación.',
  'Tu generación idealiza el hogar, la familia y las raíces.',
  'Tu generación romantiza la creatividad, el romance y el espectáculo.',
  'Tu generación espiritualiza el servicio, la salud y lo cotidiano.',
  'Tu generación idealiza el amor, la pareja y la justicia.',
  'Tu generación explora lo oculto, lo psíquico y la transformación profunda.',
  'Tu generación sueña con sentido, ideales y grandes búsquedas.',
  'Tu generación disuelve viejas estructuras y busca un nuevo orden espiritual.',
  'Tu generación idealiza la tecnología, la utopía y lo colectivo.',
  'Neptuno en su signo: generación muy sensible, mística, artística y empática.'
 ],
 'Plutón':[
  'Tu generación transforma con fuerza la identidad y la iniciativa.',
  'Tu generación transforma a fondo el dinero, los valores y los recursos.',
  'Tu generación transforma la mente, la información y la comunicación.',
  'Tu generación transforma la familia, el hogar y las raíces.',
  'Tu generación transforma el poder personal, el ego y la creatividad.',
  'Tu generación transforma el trabajo, la salud y lo cotidiano.',
  'Tu generación transforma los vínculos, la pareja y la justicia.',
  'Plutón en su signo: generación intensa y regeneradora, que va al fondo del poder.',
  'Tu generación transforma las creencias, la educación y la globalización.',
  'Tu generación transforma las estructuras de poder y las instituciones.',
  'Tu generación transforma la tecnología, lo grupal y el futuro.',
  'Tu generación transforma la espiritualidad y la conciencia colectiva.'
 ],
 Ascendente:[
  'Das una primera impresión enérgica y directa: parecés valiente, activa y sin vueltas.',
  'Das una primera impresión calma y sólida: transmitís seguridad, sensualidad y paciencia.',
  'Das una primera impresión curiosa y habladora: parecés ágil, sociable y joven.',
  'Das una primera impresión tierna y reservada: parecés sensible, protectora y cuidadosa.',
  'Das una primera impresión luminosa y segura: tenés presencia y se nota cuando entrás.',
  'Das una primera impresión prolija y discreta: parecés observadora, útil y detallista.',
  'Das una primera impresión amable y elegante: parecés diplomática, agradable y estética.',
  'Das una primera impresión magnética e intensa: parecés profunda, misteriosa y difícil de leer.',
  'Das una primera impresión expansiva y simpática: parecés aventurera, optimista y libre.',
  'Das una primera impresión seria y capaz: parecés responsable, madura y confiable.',
  'Das una primera impresión original y distinta: parecés independiente, moderna y única.',
  'Das una primera impresión dulce y soñadora: parecés sensible, artística y con un aura suave.'
 ]
};
